# Generated by Django 5.2.4 on 2026-04-16 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0002_alter_person_options_person_address_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('passport_type', models.CharField(choices=[('REGULAR', 'Regular'), ('OFFICIAL', 'Official'), ('DIPLOMATIC', 'Diplomatic')], default='REGULAR', max_length=20)),
                ('issuing_authority', models.CharField(default='U.S. Department of State', max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('SUSPENDED', 'Suspended'), ('LOST', 'Lost/Stolen')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports_issued', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='persons.person')),
            ],
        ),
    ]
