# Generated by Django 5.2.4 on 2026-04-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_applications', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REPLACED', 'Replaced'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issued_id', to='id_applications.idapplication')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_ids', to='persons.person')),
            ],
        ),
    ]
