# Generated by Django 5.2.4 on 2026-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_mfa_enabled',
            new_name='is_mfa_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('REGISTRAR', 'Registrar'), ('DMV', 'DMV'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('AUDITOR', 'Auditor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
