# Generated by Django 5.2.4 on 2026-04-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('PERMANENT_RESIDENT', 'Permanent Resident'), ('VISA_HOLDER', 'Visa Holder'), ('OTHER_LAWFUL_STATUS', 'Other Lawful Status')], max_length=50)),
                ('status_start_date', models.DateField()),
                ('status_end_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('reference_number', models.CharField(default='PENDING', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immigration_statuses', to='persons.person')),
            ],
        ),
    ]
