# Generated by Django 5.2.4 on 2026-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth_city', models.CharField(max_length=100)),
                ('place_of_birth_state', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth_country', models.CharField(default='USA', max_length=100)),
                ('citizenship_status', models.CharField(choices=[('CITIZEN', 'Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident'), ('VISA_HOLDER', 'Visa Holder'), ('OTHER', 'Other')], default='CITIZEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
